### ISSUE TITLE
error validating "redis-cluster.yml": error validating data: the server could not find the requested resource (get .apps);

### ISSUE THREAD

**Issue by rasekar2000** [sobotklp/kubernetes-redis-cluster#1]
In my MAC with Latest macOS Sierra, I am testing this one. 

RajRajen:kubernetes-redis-cluster rajrajen$ kubectl create -f redis-cluster.yml
service "redis-cluster" created
configmap "redis-cluster-config" created
**error validating "redis-cluster.yml": error validating data: the server could not find the requested resource (get .apps);** if you choose to ignore these errors, turn validation off with --validate=false
RajRajen:kubernetes-redis-cluster rajrajen$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

I will document, if I can find any reason for this issue? In the meantime, can you please check this localkube based redis-cluster with these versions specified. 

Thanks in advance.
Regards,
Raj

**Comment by rasekar2000** [comment]
Features Available in Kubernetes 1.5

**PetSet becomes StatefulSet** - PetSet's name has changed to StatefulSet in version 1.5. StatefulSet is a beta feature available in regular Container Engine clusters, and PetSet is no longer available in Alpha Clusters.
Cascading Deletion for Federated resources - You can enable cascading deletion in a cluster federation, so that when you delete a resource from the federation control plane, that resource is deleted in the underlying clusters.

I think, we need upgrade :-)

**Comment by rasekar2000** [comment]
Checking to upgrade PetSets to StatefulSet 

https://github.com/kubernetes/kubernetes.github.io/pull/1704/files

**Comment by rasekar2000** [comment]
After following these three steps from [Upgrade PetSet to StatefulSet]
(https://github.com/janetkuo/janetkuo.github.io/blob/1d9789c65d29e3b7b1f5dc5951eb1a3b6873ad2e/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set.md#prepare-statefulset-manifests)

---
1) apiVersion: apps/v1beta1
2) kind: StatefulSet

> 3) Even with  following key value pair being set with "true" or "false" the same error happens.
     annotations: 
        pod.alpha.kubernetes.io/initialized: "false"

error validating "redis-cluster.yml": error validating data: API version "apps/v1beta1" isn't supported, only supports API versions ["authorization.k8s.io/v1beta1" "batch/v1" "batch/v2alpha1" "certificates.k8s.io/v1alpha1" "rbac.authorization.k8s.io/v1alpha1" "storage.k8s.io/v1beta1" "federation/v1beta1" "apps/v1alpha1" "autoscaling/v1" "componentconfig/v1alpha1" "extensions/v1beta1" "policy/v1alpha1" "v1" "authentication.k8s.io/v1beta1"]; if you choose to ignore these errors, turn validation off with --validate=false

Now that this is clear that with my client side is on 1.4.x and server side is on 1.5.x, I may not be able to upgrade clientside Kubectl version as this is direct action from 

> gcloud components update 

Let me check if any further can be done at this time ..

**Comment by rasekar2000** [comment]
Having required kubectl version by not installing but just keeping in path ondemand..

http://kubernetes.io/docs/user-guide/prereqs/


-rwxr-xr-x   1 rajrajen  staff    48M Dec 17 12:53 kubectl
RajRajen:kubernetes-redis-cluster rajrajen$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}


RajRajen:kubernetes-redis-cluster rajrajen$ ./kubectl create -f redis-cluster.yml
statefulset "redis-cluster" created

**Comment by rasekar2000** [comment]
Merged and hence closing this ticket..

**Comment by hanson007** [comment]
I have been looking for the wrong reason this afternoon and finally found it here. Thank you!
