### ISSUE TITLE
redis-trib docker image does not exist

### ISSUE THREAD

**Issue by borg286** [sobotklp/kubernetes-redis-cluster#3]
Your readme references a docker command to reshard the cluster. Sadly the image in question does not exist in the default library for docker images.
Consider using some other user's redis-trib image. I'll let you decide who is updating frequently enough.

**Comment by borg286** [comment]
After having used redit-trib.rb I've found that you should probably use an image that is based off of unstable or 4.0 as he has some changes that make the fix operation better.

**Comment by sobotklp** [comment]
Thanks! If you can suggest an image to use, I'm all ears. I was planning on creating my own docker image that includes redis-trib.rb as well as some scripts to initialize Redis Cluster, but I haven't had time to work on this project for several months now :(

**Comment by borg286** [comment]
Try zvelo/redis-trib
I'm finding that your resharding instructions are broken. I've verified that baremetal redis clustering is working as intended with your instructions, but when placed within kubernetes it doesn't. I'm trying to strip your configuration down to see if I can reshard. I'll use the above image to perform the resharding and I'll try to remember to get back on this post and report my success, or tell you to use a different image of redis-trib that incorporates any needed patches. I don't think it'll need it. I just want to figure out what works and what doesn't when redis is NATed.

**Comment by Ivanknmk** [comment]
@borg286 Having the same issue resharding. Have you had the chance to figure out what's wrong?

**Comment by sobotklp** [comment]
I haven't had time to investigate this, no. I had an issue several months ago when I was using an older version of redis-trib.rb that was erroring out when trying to reshard. I got around this by using a newer version of redis-trib.rb, but never added that to a Docker image.

**Comment by sobotklp** [comment]
Closing this because the latest update drastically changes the way the cluster is initialized. The new version requires at least Redis 5, which adds much better cluster initialization functions to redis-cli. Now it will properly distribute the slots across the first 3 StatefulSet nodes, with the remaining nodes joining as replicas of the initial ones.
