### ISSUE TITLE
New bootstrap script

### ISSUE THREAD

**Issue by borg286** [sobotklp/kubernetes-redis-cluster#4]
While playing with your yaml file I found I needed the following changes to get it to work.
The problem I was facing was that when nodes 1-5 start up and meet the master, and then mark themselves as slaves, that the master no longer allows migration of nodes to them, because it thinks they are still slaves. I've followed your instructions and verified that the master shows "cluster nodes" as having 2 masters with the second one not having any slots. Yet when I use redis-trib it fails. I've tried to do this on barebones and roughly following your script it seems to work fine. My guess is that we find some race condition wherein the master meets the other servers, marks them as masters, node {2,5} mark themselves as slaves; the master marks them accordingly; manually I soft reset (even hard reset doesn't work); but the master-0 doesn't reflect this change in its internal flags that it uses to know if it is a slave or not.

The fix I tried to do was to never have the nodes 1-6 becoming slaves, but instead stay as masters.
I had to replicate some of the logic in redis-trib for the resharding part.
But now it should be easy to reshard and rebalance the cluster.

One thing in addition to this I added to the container was
```
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

```
#
# A script to bootstrap PetSet members as they initialize
# TODO: Move this logic into a separate Docker image. We shouldn't be doing this kind of hackery here.
#
  bootstrap-pod.sh: |+
    #!/bin/sh
    set -e

    # Find which member of the PetSet this pod is running
    # e.g. "redis-cluster-0" -> "0"
    PET_ORDINAL=$(cat /etc/podinfo/pod_name | rev | cut -d- -f1)

    redis-server /conf/redis.conf &

    # TODO: Wait until redis-server process is ready
    sleep 1

    if [ $PET_ORDINAL = "0" ]; then
      # The first member of the cluster should control all slots initially
      redis-cli cluster addslots $(seq 0 16383)
    elif [ $(($PET_ORDINAL%2)) -eq 0 ]; then
      # All other even nodes meet redis-cluster-0 as a master and peer, but with no slots.
      PEER_IP=$(perl -MSocket -e 'print inet_ntoa(scalar(gethostbyname("redis-cluster-0.redis-cluster.default.svc.cluster.local")))')
      echo "Meeting master $PEER_IP"
      redis-cli cluster meet $PEER_IP 6379
      sleep 1


      echo "Fetching master ID"
      MASTER_ID=$(redis-cli --csv cluster slots | cut -d, -f 5 | sed -e 's/^"//'  -e 's/"$//')
      echo "fetching my ID"
      MY_ID=$(redis-cli --csv cluster nodes | grep myself | cut -d' ' -f1 | sed -e 's/^"//'  -e 's/"$//')

      keys=$(redis-cli -h $PEER_IP cluster getkeysinslot $PET_ORDINAL 1)

      echo "Preparing slot $PET_ORDINAL for import"
      redis-cli cluster setslot $PET_ORDINAL importing $MY_ID

      echo "Preparing Master slot for migration"
      redis-cli -h $PEER_IP cluster setslot $PET_ORDINAL migrating $MY_ID

      echo "Telling master to migrate the following keys $keys"
      redis-cli -h $PEER_IP migrate $MY_POD_IP 6379 "" 0 5000 KEYS $keys

      echo "Telling master that I now own this slot"
      redis-cli -h $PEER_IP cluster setslot $PET_ORDINAL node $MY_ID
    else
      # Other members of the cluster join as slaves
      # TODO: Get list of peers using the peer finder using an init container
      export TARGET_INDEX=$(($PET_ORDINAL-1))
      echo "Attaching myself to redis cluster $TARGET_INDEX"
      PEER_IP=$(perl -MSocket -e 'print inet_ntoa(scalar(gethostbyname("redis-cluster-".$ENV{"TARGET_INDEX"}.".redis-cluster.default.svc.cluster.local")))')
      echo "Meeting my master's IP $PEER_IP"
      redis-cli cluster meet $PEER_IP 6379
      sleep 1

      # Become the slave of the previous node (ie. redis-cluster-<i-1>)
      echo "Fetching master ID"
      MASTER_ID=$(redis-cli --csv cluster nodes | grep $PEER_IP  | cut -d' ' -f 1 | sed -e 's/^"//'  -e 's/"$//')
      redis-cli cluster replicate $MASTER_ID
    fi

```

**Comment by borg286** [comment]
I correct my above solution. The code is right, but the nutshell should be the following
The 0'th server is the first master and claims all slots
all odd numbered servers meet the redis server just below them (1 meets 0, 3 meets 2...) and become slaves
All other even servers meet 0 as masters, and migrate a single slot to themselves, namely the slot corresponding to their position in the fleet.

I wanted to validate that a subsequent resharding wouldn't fail complaining that the slot owner thinks the target server is a slave.

The nice thing about this solution is that as you increase the replica count, each joins the fleet or becomes a slave (to maintain redundancy). 

One improvement I guess is that each even master picks a random slot owned by the 0 master to claim it. This way if you rebalance then increase replica count, the new masters won't barf trying to claim a slot that got reshuffled.

**Comment by borg286** [comment]
I actually did just that. Now the script will pick a random slot for even redis nodes to claim from the first master.

```
  bootstrap-pod.sh: |+
    #!/bin/sh
    set -e

    # Find which member of the PetSet this pod is running
    # e.g. "redis-cluster-0" -> "0"
    PET_ORDINAL=$(cat /etc/podinfo/pod_name | rev | cut -d- -f1)

    redis-server /conf/redis.conf &

    # TODO: Wait until redis-server process is ready
    sleep 1

    if [ $PET_ORDINAL = "0" ]; then
      # The first member of the cluster should control all slots initially
      redis-cli cluster addslots $(seq 0 16383)
      sleep 2
      for i in a b c d e f g h i j k l m n o p q r s t u v w x y z; do redis-cli set $i 0; done
    elif [ $(($PET_ORDINAL%2)) -eq 0 ]; then
      # All other even nodes meet redis-cluster-0 as a master and peer, but with no slots.
      MASTER_IP=$(perl -MSocket -e 'print inet_ntoa(scalar(gethostbyname("redis-cluster-0.redis-cluster.default.svc.cluster.local")))')
      echo "Meeting master $MASTER_IP"
      redis-cli cluster meet $MASTER_IP 6379
      sleep 1


      MASTER_ID=$(redis-cli --csv cluster nodes | grep $MASTER_IP | cut -d' ' -f 1 | sed -e 's/^"//'  -e 's/"$//')
      echo "First Master's ID: $MASTER_ID"
      MY_ID=$(redis-cli --csv cluster nodes | grep myself | cut -d' ' -f1 | sed -e 's/^"//'  -e 's/"$//')
      echo "My ID: $MY_ID"

      random_key=$(redis-cli -h $MASTER_IP randomkey)
      if [ -z "$random_key" ]; then
        # default to the slot matching the position of this redis pod. It is guaranteed to not collide with anyone else.
        TARGET_SLOT=$PET_ORDINAL
      else
        # The master has a key,
        TARGET_SLOT=$(redis-cli -h $MASTER_IP cluster keyslot $random_key)
      fi

      keys=$(redis-cli -h $MASTER_IP cluster getkeysinslot $TARGET_SLOT 999999999)

      echo "Preparing slot $TARGET_SLOT for import"
      redis-cli cluster setslot $TARGET_SLOT importing $MY_ID

      echo "Preparing Master slot for migration"
      redis-cli -h $MASTER_IP cluster setslot $TARGET_SLOT migrating $MY_ID

      echo "Telling master to migrate the following keys $keys"
      redis-cli -h $MASTER_IP migrate $MY_POD_IP 6379 "" 0 5000 KEYS $keys

      echo "Telling master that I now own this slot"
      redis-cli -h $MASTER_IP cluster setslot $TARGET_SLOT node $MY_ID
    else
      # Other members of the cluster join as slaves
      # TODO: Get list of peers using the peer finder using an init container
      export TARGET_INDEX=$(($PET_ORDINAL-1))
      echo "Attaching myself to redis cluster $TARGET_INDEX"
      MASTER_IP=$(perl -MSocket -e 'print inet_ntoa(scalar(gethostbyname("redis-cluster-".$ENV{"TARGET_INDEX"}.".redis-cluster.default.svc.cluster.local")))')
      echo "Meeting my master's IP $MASTER_IP"
      redis-cli cluster meet $MASTER_IP 6379
      sleep 1

      # Become the slave of the previous node (ie. redis-cluster-<i-1>)
      echo "Fetching master ID"
      MY_MASTER_ID=$(redis-cli --csv cluster nodes | grep $MASTER_IP  | cut -d' ' -f 1 | sed -e 's/^"//'  -e 's/"$//')
      redis-cli cluster replicate $MY_MASTER_ID
    fi

    wait
```

**Comment by sobotklp** [comment]
Initially I had issues with redis-trib as well. I found that using outdated versions of redis-trib.rb would fail for more recent versions of Redis server.

I used the above bootstrap-pod.sh that you provided (thank-you so much by the way!!) and it indeed created 3 master nodes and 3 slave nodes. However, I'm not sure that it evenly distributed hash slots among the masters.

Specifically, this output of redis-cli cluster nodes shows the config of Pod redis-cluster-0:
`67b7bacba42ea14f2092d48b4170a83b14193b1f 172.17.0.4:6379 myself,master - 0 0 1 connected 0-16383 [3564->-a81bf3887f5bd2aac23e69ce5de1380c785d924c] [15495->-8501c350259d08dc49cb51e66f05f85ae8dce757]`

**Comment by borg286** [comment]
I did not intend to have my bootstrap script try to balance out the cluster. The main reason is that I wanted first to validate that I could create a functional cluster with pod replacement. Balancing it out would be delegated to a cron job. If every pod that was added tried to mess with the entire cluster it would create quite a bit of noise and extra network churn while I was testing.

In the end the prefered method would be to have additional nodes ask for slots from a bunch of  masters and balance itself with the rest of the cluster. Departing pods would try to return slots. This was too much for my little brain and time. Getting it bootstrapped was a good foundation for my goals.

**Comment by sanderploegsma** [comment]
This is a nice start, although after migrating the slots the cluster is kind of in a weird state: the first master is up-to-date on which slot resides in which master, but the other two are never updated. In my case the slot containing `j` was migrated, but running `GET j` ends up in an infinite loop of masters redirecting to each other...

**Comment by sobotklp** [comment]
Closing this because the latest update drastically changes the way the cluster is initialized. Now it will properly distribute the slots across the first 3 StatefulSet nodes, with the remaining nodes joining as replicas of the initial ones.
