### ISSUE TITLE
i have played with your yaml on kubernetes 1.6 but ... maybe i need your help 

### ISSUE THREAD

**Issue by planktonzp** [sobotklp/kubernetes-redis-cluster#5]
it runs normal but i cannot get the others cluster nodes

for a in $(seq 0 6); do kubectl exec -ti redis-$a --namespace=dipper redis-cli cluster nodes; done

7e1d4fe27626cd20dc978c53eb6a9cd50b522dd5 :6379 myself,master - 0 0 0 connected

833c424629b8acc7183421057878915ac94791bf :6379 myself,master - 0 0 0 connected

31c0195481f3314429e222cf4adf60aefecf38ad :6379 myself,master - 0 0 0 connected

dcbb5682a1c47cc63093308a5b38904e4769366b :6379 myself,master - 0 0 0 connected

95e8250641eaedcd5a4a42e048dc3dbb71cd19c7 :6379 myself,master - 0 0 0 connected

37d5fcf9d1a5e4e774a34a0871c4f020bcee626b :6379 myself,master - 0 0 0 connected

2bc6df26211b063c0b73ee4cde25bffce226507f :6379 myself,master - 0 0 0 connected

please help me thx Orz

**Comment by valentin2105** [comment]
Yeah it seem to don't work on recent cluster,

peer-finder stuck after the download, Any idea why ? 

I will try to push a fix if I find the time !

**Comment by planktonzp** [comment]
i have writen a new yaml in my repositories maybe it will work in a kubernetes cluster (1.6+),and it still have lots of bug .if you'd like help me fix it , i'll be indebted 
here is the yaml [https://github.com/ruizhipeng/kubernetes-redis-cluster/blob/master/redis-cluster.yml](url)

**Comment by KeithTt** [comment]
Any update?

**Comment by sobotklp** [comment]
Closing this because the latest update drastically changes the way the cluster is initialized. Now it will properly distribute the slots across the first 3 StatefulSet nodes, with the remaining nodes joining as replicas of the initial ones.
